### PR TITLE
Add spill to disk setting doc

### PR DESCRIPTION
**Pull request by benjaminwinger**

### CODE REVIEW

**Review by prrao87 — APPROVED** [review]
Looks good - will hold off on merging till this is available in the next release.

**Comment by benjaminwinger** [comment]
Right, sorry, should this have gone into the dev branch instead, or is that for something else?

**Comment by prrao87** [comment]
No, I added the required labels to this and will ensure it goes to the live branch once we release. Thanks!

**Comment by benjaminwinger** [comment]
I've added a section in the import docs explaining the feature, and also added documentation for when spill to disk is disabled by default, and how it can be disabled manually.

**Review by prrao87 — COMMENTED** [review]
Looks good, will hold off on merging this till the release.

**Pull request merged**
