### PR TITLE
Add Preliminary Docs for Python UDF support

### LINKED ISSUE #151: Add documentation for Python UDF
UDF has already been implemented in master, we should write doc for python udf before next release.

### PR DESCRIPTION
**Pull request by mxwli**
Closes #151 when merged.

### CODE REVIEW

**Comment by mxwli** [comment]
Update: I'm changing the way params_type works so that part may become outdated.

**Comment by mxwli** [comment]
"extra features" have not been merged with master yet.

**Comment by prrao87** [comment]
@mxwli is this part of the docs ready for review? I've changed the destination branch to the 0.5.0 branch so that it can go in with the rest of the updates.

**Review by prrao87 — APPROVED** [review]
LGTM, adding this to the 0.5.0 branch and continuing work there after running some more tests.

**Pull request merged**
